[2024-02-16T18:19:19.457+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: mlb_dag.player_lookup manual__2024-02-16T18:19:17.675593+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
